spring.application.name=PaymentService


server.port=8080
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.type.mapping=enrollment:com.cfs.PaymentService.model.EnrollmentNotification

# Razorpay Credentials
app.razorpay.api.key-id=rzp_test_SjZYZiV8SdQ9dx
app.razorpay.api.key-secret=g7RyTf4Wbty7ZZv9YUmb3OJP
app.kafka.topic=course-enrollment-notification
app.cors.allowed-origin-patterns=http://localhost:*,http://127.0.0.1:*
